In [1]:
from src.process_EDF import *

/Users/prakharagrawal/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


# Calculation_code

`06_month`, `12_month` and `24_month`, for now, can be toggled through the file `process_EDF.py` by editing `INPUT_PATH` and `OUTPUT PATH`.

In [2]:
from os import walk

directory = os.getcwd()
full_path = directory+'/'+INPUT_PATH

for (dirpath, dirnames, filenames) in walk(INPUT_PATH):
    file_list = [full_path+'/'+f for f in filenames if f.lower().endswith('.edf')]

print(file_list)

output = directory+'/'+OUTPUT_PATH

if not os.path.exists(output):
    os.makedirs(output)
    print("output folder created")

['/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170609144142_A11-1-1.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170127133329_A1-1-1.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170106141207_A4-1-1.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170512131252_A13-2-2.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170609155718_A8-3-3.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170512131641_A13-2-2.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170113105900_A6-1-1.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170519093503_A2-1-1.edf', '/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170609163157_A8-2-3.edf', '/Users/prakharagrawal/Downloads/

In [ ]:
#pool = mp.Pool(processes=4)
#pool.map(process, file_list)
process(file_list[9])

### Attempt : 1
Processing /Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170113104343_A6-1-1.edf
Setting levels...
Setting frequency bands...
### before compute_feautres
Setting features....
Computing Non RQA features....


  0%|          | 0/8 [00:00<?, ?it/s]

Power 0 [-4708515.15044583 -4482511.67930516 -4237507.91634293 ...
    38057.75118781    40057.78190587    32557.66671315] Fp1
SampE 0 [-4708515.15044583 -4482511.67930516 -4237507.91634293 ...
    38057.75118781    40057.78190587    32557.66671315] Fp1
hurstrs 0 [-4708515.15044583 -4482511.67930516 -4237507.91634293 ...
    38057.75118781    40057.78190587    32557.66671315] Fp1
dfa 0 [-4708515.15044583 -4482511.67930516 -4237507.91634293 ...
    38057.75118781    40057.78190587    32557.66671315] Fp1
lyap0 0 [-4708515.15044583 -4482511.67930516 -4237507.91634293 ...
    38057.75118781    40057.78190587    32557.66671315] Fp1


# Function exploration:

In [37]:
f = pyedflib.EdfReader(file_list[9])

In [42]:
data = data_obj.data[0]

In [38]:
f.getHeader()

{'technician': '',
 'recording_additional': '',
 'patientname': '',
 'patient_additional': '',
 'patientcode': '',
 'equipment': '',
 'admincode': '',
 'gender': '',
 'startdate': datetime.datetime(2017, 1, 13, 10, 43, 43),
 'birthdate': ''}

In [9]:
f.signals_in_file

8

In [11]:
for i in range(f.signals_in_file):
    print(f.getSampleFrequency(i))

500
500
500
500
500
500
500
500


In [14]:
import types

skip_instances_tuple = (types.BuiltinFunctionType, types.MethodType,
                       types.BuiltinMethodType, types.FunctionType)

def print_object_attrs(obj):

   object_attributes = [atr for atr in obj.__dir__() if not atr.startswith('__')]

   for atr in object_attributes:
       t = getattr(obj, atr)
       if not isinstance(t, skip_instances_tuple):
           print(f"{atr}: {getattr(obj, atr)} \n")
print_object_attrs(f)

file_name: /Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170113104343_A6-1-1.edf 

handle: 0 

datarecords_in_file: 223 

signals_in_file: 8 

file_duration: 223 

patient: b'N/A                                                                             ' 

datarecord_duration: 1.0 

annotations_in_file: 0 

patientcode: b'' 

gender: b'' 

birthdate: b'' 

patientname: b'' 

patient_additional: b'' 

startdate_year: 2017 

startdate_month: 1 

startdate_day: 13 

starttime_hour: 10 

starttime_minute: 43 

starttime_second: 43 

admincode: b'' 

technician: b'' 

equipment: b'' 

recording_additional: b'' 



In [17]:
f.readSignal(0).shape

read -1, less than 111500 requested!!!


(111500,)

In [ ]:
print(f'Processing {filepath}')
f = pyedflib.EdfReader(filepath)         # read the edf file 

headers = f.getHeader()
start_dt = headers.pop('startdate', None) #startdate

channelNames = f.getSignalLabels()       # channelnames
srate = f.getSampleFrequency(3)          # sampling rate
n = f.signals_in_file                    # number of signals 
data = np.zeros((n, f.getNSamples()[0])) 
for i in np.arange(n):
    data[i, :] = f.readSignal(i)         # shitty implementation of pyedflib 
nt = max_nt*srate                        # number of time periods
if data.shape[1] > 60*srate:
    m1 = 30*srate
else:
    m1 = 0                               # start time                          
m2 = m1 + nt                             # end time
data = data[:,m1:m2]                     # truncating data to the max number of time periods (in s)

In [7]:
file_list[9]

'/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170113104343_A6-1-1.edf'

# Sparkify:

In [21]:
from pathlib import Path
import pyedflib
import pywt
import numpy as np
import nolds
from pyrqa.time_series import SingleTimeSeries
from pyrqa.settings import Settings
from pyrqa.neighbourhood import FixedRadius
from pyrqa.computation import RQAComputation
#from pyspark import SparkContext
from math import log2

In [19]:
#sc = SparkContext.getOrCreate()
filepath = Path("/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170127132258_A1-1-1.edf")

In [2]:
f = pyedflib.EdfReader(str(filepath))

In [3]:
rawdata = f.readSignal(0)

In [41]:
all_features = ["Power", "SampE", "hurstrs","dfa", "lyap0", "lyap1", "lyap2", 
                "RR", "DET", "LAM", "Lentr", "Lmax", "Lmean", "TT"]

nonrqa_features = ['Power','SampE','hurstrs','dfa','lyap0','lyap1','lyap2']

rqa_features = ["RR", "DET", "LAM", "Lentr", "Lmax", "Lmean", "TT"]

#srate = 500
wavelet = 'db4'
mode = 'cpd'
embedding, tdelay, tau = 10, 2, 30

In [42]:
from pyrqa.opencl import OpenCL
opencl = OpenCL(platform_id=0,
                device_ids=(0,1,))

In [30]:
def power(y): return np.sum(y**2)/y.size
def sampE(y): return nolds.sampen(y)
def hurstrs(y): return nolds.hurst_rs(y)
def dfa(y): return nolds.dfa(y)
def lyap(y,emb_dim): return nolds.lyap_e(y, emb_dim)
def RR(result): return result.recurrence_rate
def DET(result): return result.determinism
def LAM(result): return result.laminarity
def Lentr(result): return result.entropy_diagonal_lines
def Lmax(result): return result.longest_diagonal_line
def Lmean(result): return result.average_diagonal_line
def TT(result): return result.trapping_time

function_dict = {"Power": power,"SampE":sampE, "hurstrs":hurstrs,
                 "dfa": dfa,"lyap":lyap,"RR": RR, "DET": DET, 
                 "LAM": LAM, "Lentr": Lentr,"Lmax":Lmax,
                 "Lmean":Lmean,"TT":TT }

In [4]:
def trim_data(data, max_nt, srate):
    nt = max_nt*srate                        # number of time periods
    if data.shape[0] > 60*srate:
        m1 = 30*srate
    else:
        m1 = 0                               # start time                          
    m2 = m1 + nt                             # end time
    trim_data = data[m1:m2]                     # truncating data to the max number of time periods (in s)
    return trim_data

In [5]:
def features_settings(wavelet, mode, srate, data):
    w = pywt.Wavelet(wavelet)
    a_orig = data - np.mean(data)
    a = a_orig
    nbands = int(log2(srate))-1

    rec_a,rec_d = [] ,[]               # all the approximations and details

    for i in range(nbands):
        (a, d) = pywt.dwt(a, w, mode)
        f = pow(np.sqrt(2.0), i+1)
        rec_a.append(a/f)
        rec_d.append(d/f)

    f_labels,freqband = ['A0'],[a_orig] # A0 is the original signal
    fs = [srate]
    f = fs[0] 
    N = len(a_orig)

    for j,r in enumerate(rec_d):
        freq_name = 'D' + str(j+1)
        f_labels.append(freq_name)
        freqband.append(r[0:N])          # wavelet details for this band
        fs.append(f)
        f = f/2.0

    # We need one more
    f = f/2.0
    fs.append(f)

    j = len(rec_d)-1
    freq_name = 'A' + str(j+1)
    f_labels.append(freq_name)
    freqband.append(rec_a[j])       # wavelet approximation for this band
    return freqband, f_labels

In [38]:
def compute_non_rqa_features(freqband, f_labels, nonrqa_features):
    feature_calc = dict()
    error_count = 0

    for i, y in enumerate(freqband):
        for feat in nonrqa_features:
            if feat in all_features:
                if feat.startswith('lyap'):
                    try:
                        lyap = function_dict['lyap'](y,self.embedding)
                        num = int(feat[-1])
                        feature_calc[feat+"_"+f_labels[i]] = lyap[num]
                    except:
                        feature_calc[feat+"_"+f_labels[i]] = np.nan
                        error_count += 1
                else:
                    try:
                        feature_calc[feat+"_"+f_labels[i]] = function_dict[feat](y)
                    except:
                        feature_calc[feat+"_"+f_labels[i]] = np.nan
                        error_count += 1
    return feature_calc, error_count

In [39]:
def compute_rqa_features(freqband, f_labels, rqa_features):
    feature_calc = dict()
    error_count = 0

    for i, y in enumerate(freqband):
#         print('aaaa', i, y)
#         print(embedding)
        y = SingleTimeSeries(y, embedding_dimension=embedding, time_delay=tdelay)
        settings = Settings(y, neighbourhood=FixedRadius(tau))
        computation = RQAComputation.create(settings, verbose=True, opencl=opencl)
        result = computation.run()
        #print(result)

        for feat in rqa_features:
            if feat in all_features:
                try:
                    feature_calc[feat+"_"+f_labels[i]] = function_dict[feat](result)
                except:
                    feature_calc[feat+"_"+f_labels[i]] = np.nan
                    error_count += 1
    return feature_calc, error_count

In [ ]:
data_1 = trim_data(rawdata, max_nt= 30, srate = srate)
freqband_1, f_labels_1 = features_settings(wavelet, mode, srate, data_1)

In [36]:
feature_calc_1, error_count_1 = compute_non_rqa_features(freqband_1, f_labels_1, nonrqa_features)

In [43]:
feature_calc_2, error_count_2 = compute_rqa_features(freqband_1, f_labels_1, rqa_features)

In [40]:
feature_calc_1, feature_calc_2

({'Power_A0': 233597197715.3329,
  'SampE_A0': 0.022548536044970372,
  'hurstrs_A0': 0.9719444175489373,
  'dfa_A0': 1.6085560354971882,
  'lyap0_A0': nan,
  'lyap1_A0': nan,
  'lyap2_A0': nan,
  'Power_D1': 8527497.321728902,
  'SampE_D1': 1.257659308990407,
  'hurstrs_D1': 0.40187530172043917,
  'dfa_D1': 0.40635819176698895,
  'lyap0_D1': nan,
  'lyap1_D1': nan,
  'lyap2_D1': nan,
  'Power_D2': 64174880.09890159,
  'SampE_D2': 0.8232831249554935,
  'hurstrs_D2': 0.39637232489862606,
  'dfa_D2': 0.4660449823071643,
  'lyap0_D2': nan,
  'lyap1_D2': nan,
  'lyap2_D2': nan,
  'Power_D3': 229081094.21121573,
  'SampE_D3': 0.6721229781042434,
  'hurstrs_D3': 0.4496811350769011,
  'dfa_D3': 0.5994571692676924,
  'lyap0_D3': nan,
  'lyap1_D3': nan,
  'lyap2_D3': nan,
  'Power_D4': 444468180.7959044,
  'SampE_D4': 0.7098300719668436,
  'hurstrs_D4': 0.4062347222679008,
  'dfa_D4': 0.5598787113386988,
  'lyap0_D4': nan,
  'lyap1_D4': nan,
  'lyap2_D4': nan,
  'Power_D5': 2840056349.3257966,
 

In [33]:
error_count_1, error_count_2

(27, 0)

# Extra

In [82]:
data = data_obj.data[0]

In [100]:
class Single_Channel:
    
    def __init__(self,rawdata,max_nt):
        self.D = {}
        self.data = self.extract_from(rawdata, max_nt,srate)
    
    def extract_from(self, data, max_nt, srate):
        nt = max_nt*srate                        # number of time periods
        if data.shape[0] > 60*srate:
            m1 = 30*srate
        else:
            m1 = 0                               # start time                          
        m2 = m1 + nt                             # end time
        data = data[m1:m2]                     # truncating data to the max number of time periods (in s)
        return data

In [102]:
a1 = Single_Channel(rawdata,max_nt=30)

In [105]:
a1.data

array([16742753.87155184, 16747753.94834699, 16737253.78707718, ...,
       16426749.01809851, 16425248.99505997, 16425749.00273948])

In [83]:
srate = 500
wavelet = 'db4'
mode = 'cpd'
embedding, tdelay, tau = 10, 2, 30 # RQA parameters: embed_dim, time_delay, threshold

In [86]:
def set_f_limit(srate):
    nbands = int(log2(srate))-1
    f_limit = np.ones(nbands+1) * srate / (2.0 **(nbands+1))
    f_limit[bands] = srate / 2.0
    for i in range(1,nbands):
        f_limit[i] = f_limit[i-1] * 2.0
    f_limit[0] = 0.0
    return f_limit

In [87]:
f_limit = set_f_limit(srate)

array([  0.     ,   3.90625,   7.8125 ,  15.625  ,  31.25   ,  62.5    ,
       125.     , 250.     ])

In [111]:
freqband,f_labels = features_settings(wavelet, mode, srate, data)

In [113]:
freqband

[array([357598.52561529, 362598.60241044, 352098.44114063, ...,
         41593.67216196,  40093.64912342,  40593.65680293]),
 array([ -814.52108019, -1915.49791537,  1577.7056247 , ...,
          179.71655658,   -41.65001001,     3.74680488]),
 array([-2.62275332e+01, -5.63036837e+02, -5.91552552e+03, ...,
        -9.41131417e+01, -1.39820793e+01, -2.16004992e-12]),
 array([ 2.91239773e+00, -2.98770180e+02,  1.63846833e+03, ...,
        -2.12584730e+02, -3.52649133e+01,  9.24470440e-13]),
 array([ 2.38393508e+00,  2.23816450e+02,  6.32040847e+03, -9.61185419e+03,
         1.74416810e+04,  2.47520151e+02,  2.76808120e+02,  1.81455394e+03,
         2.63039838e+03, -3.87709875e+03,  2.00819608e+04, -7.56373944e+03,
         1.67930428e+04,  1.00014788e+03, -4.66332804e+03,  5.65388566e+03,
        -1.39020034e+03, -1.13224942e+04,  1.88685734e+04, -9.46634546e+02,
        -5.09345973e+03,  1.09442718e+04, -6.65694159e+03, -4.82958135e+03,
         7.43523650e+03, -3.98053853e+03,  1.37751

In [78]:
feature_calc = dict()

In [79]:
nonrqa_features = ['Power','SampE','hurstrs','dfa','lyap0','lyap1','lyap2']

In [80]:
feature_calc

{'Power_A0': 233597197715.3329,
 'SampE_A0': 0.022548536044970372,
 'hurstrs_A0': 0.9719444175489373,
 'dfa_A0': 1.6085560354971882,
 'lyap0_A0': nan,
 'lyap1_A0': nan,
 'lyap2_A0': nan,
 'Power_D1': 8527497.321728902,
 'SampE_D1': 1.257659308990407,
 'hurstrs_D1': 0.40187530172043917,
 'dfa_D1': 0.40635819176698895,
 'lyap0_D1': nan,
 'lyap1_D1': nan,
 'lyap2_D1': nan,
 'Power_D2': 64174880.09890159,
 'SampE_D2': 0.8232831249554935,
 'hurstrs_D2': 0.39637232489862606,
 'dfa_D2': 0.4660449823071643,
 'lyap0_D2': nan,
 'lyap1_D2': nan,
 'lyap2_D2': nan,
 'Power_D3': 229081094.21121573,
 'SampE_D3': 0.6721229781042434,
 'hurstrs_D3': 0.4496811350769011,
 'dfa_D3': 0.5994571692676924,
 'lyap0_D3': nan,
 'lyap1_D3': nan,
 'lyap2_D3': nan,
 'Power_D4': 444468180.7959044,
 'SampE_D4': 0.7098300719668436,
 'hurstrs_D4': 0.4062347222679008,
 'dfa_D4': 0.5598787113386988,
 'lyap0_D4': nan,
 'lyap1_D4': nan,
 'lyap2_D4': nan,
 'Power_D5': 2840056349.3257966,
 'SampE_D5': 0.3305742223098008,
 'hu

In [81]:
print(error_count)

27


In [ ]:
self.f_labels,self.freqband = ['A0'],[a_orig] # A0 is the original signal
fs = [self.srate]
f = fs[0] 
N = len(a_orig)

for j,r in enumerate(rec_d):
    freq_name = 'D' + str(j+1)
    self.f_labels.append(freq_name)
    self.freqband.append(r[0:N])          # wavelet details for this band
    fs.append(f)
    f = f/2.0

# We need one more
f = f/2.0
fs.append(f)

# Keep only the last approximation
j = len(rec_d)-1
freq_name = 'A' + str(j+1)
self.f_labels.append(freq_name)
self.freqband.append(rec_a[j])       # wavelet approximation for this band

for f in all_features:
    self.D[ch][f] = {}

# Experimentation:

In [31]:
from pathlib import Path
filepath = Path("/Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170127132258_A1-1-1.edf")

In [32]:
data_obj = Data(str(filepath),max_nt=30)

Processing /Users/prakharagrawal/Downloads/MSDS697/Rutgers/EEG_MSDS697/data/06_month_EEG/20170127132258_A1-1-1.edf
Setting levels...
Setting frequency bands...


In [33]:
data_obj.f_limit

array([  0.     ,   3.90625,   7.8125 ,  15.625  ,  31.25   ,  62.5    ,
       125.     , 250.     ])

In [5]:
rqa_features = ["RR", "DET", "LAM", "Lentr", "Lmax", "Lmean", "TT"]

In [6]:
data_obj.compute_features(all_features,master_channel_list,function_dict)

 38%|███▊      | 3/8 [00:00<00:00, 23.12it/s]

Setting features....
Computing Non RQA features....
Power 0 [64177.66118226 81627.53953733 70409.76059478 ...  7198.46655343
 -2060.65257375   788.30715769] Fp1
Power 1 [-2842.61509358 -2806.83942453  1190.01876379 ...   953.44753037
  -279.22715776    21.34866455] Fp1
Power 2 [-1.20592561e+02 -3.37208075e+03 -9.23894083e+03 ...  9.60609692e+01
 -1.50912721e+02  1.33226763e-14] Fp1
Power 3 [ 1.92604714e+01  1.38268280e+02  2.69203650e+03 ... -1.80164053e+02
 -1.99502058e+02  1.94691465e-14] Fp1
Power 4 [-7.65117998e-02  1.79268349e+02  4.73894456e+03 -1.04842122e+02
  5.46068463e+03 -5.30714813e+03  2.39431885e+03  9.07577050e+03
  8.58586729e+03 -9.82724842e+03 -2.05697110e+01  4.15554275e+03
  7.64066172e+03  2.35771749e+03  9.48333831e+02  9.40568834e+03
 -3.05735362e+03  1.34834603e+03 -7.33991826e+02  6.90068822e+02
  1.45008982e+04  1.81721969e+04 -1.57947764e+04  1.20094083e+04
 -7.39573525e+03 -4.48554784e+03  3.41604211e+03  3.68272593e+03
 -3.20202494e+03 -6.11698036e+03  1.4

 62%|██████▎   | 5/8 [00:00<00:00, 19.84it/s]

[-7.65117998e-02  1.79268349e+02  4.73894456e+03 -1.04842122e+02
  5.46068463e+03 -5.30714813e+03  2.39431885e+03  9.07577050e+03
  8.58586729e+03 -9.82724842e+03 -2.05697110e+01  4.15554275e+03
  7.64066172e+03  2.35771749e+03  9.48333831e+02  9.40568834e+03
 -3.05735362e+03  1.34834603e+03 -7.33991826e+02  6.90068822e+02
  1.45008982e+04  1.81721969e+04 -1.57947764e+04  1.20094083e+04
 -7.39573525e+03 -4.48554784e+03  3.41604211e+03  3.68272593e+03
 -3.20202494e+03 -6.11698036e+03  1.46762910e+03  7.28366353e+03
 -7.08815810e+03  6.26527321e+03  1.65627349e+04 -1.13002153e+04
 -5.94237820e+03  8.18745193e+04 -1.11871349e+05 -1.79980720e+03
  1.33557104e+04  1.71005877e+03 -3.46114189e+03  5.84347762e+03
 -2.14588354e+04  1.02233590e+04  5.67727328e+03  2.07826490e+04
 -1.08905378e+04  1.35756076e+04 -8.31317483e+03 -1.87896903e+04
  2.84990128e+04  4.44445668e+04  1.49893100e+04  2.33012094e+04
 -8.80893542e+03 -7.27519100e+04  6.58389779e+04 -1.91212134e+04
 -4.61220798e+03 -9.36859

100%|██████████| 8/8 [00:00<00:00, 15.42it/s]

[-1.84024156e+00  2.52819156e+02  9.91109611e+03 -4.80872467e+03
 -1.07937401e+05 -2.71994222e+04  5.52995023e+04  6.70255238e+05
 -2.80398113e+05 -1.29767648e+05  2.65422783e+05 -1.87040464e+05
  8.38596062e+04 -8.14143215e+04  1.21183163e+04  9.09168366e+03
  5.01616085e+05  3.94615579e+05 -2.52638968e+05 -2.70847636e+05
  1.68695763e+05  4.14805611e+05  2.10549877e+03 -8.89572582e+04
  2.15340150e+04  6.79257981e+03  1.43792723e+05 -4.17885092e+04
  2.06670935e+04  1.51761040e+04 -6.04848165e+04  6.06807980e+04
  8.54800326e+02 -2.16297348e+04  1.91881569e+04 -3.97744552e+04
  2.19361561e+04 -6.56060118e+04  3.19809173e+04 -9.91774096e+01
 -4.21137982e+04  1.22078605e+04  4.22927449e+04 -1.63955398e+04
 -4.10879054e+04  9.73762777e+03 -4.36616734e+03  4.19969289e+03
 -4.24050221e+02  2.32376334e+04  1.52882881e+04 -6.97552704e+04
 -1.03243339e+04  5.63582792e+03 -5.28247527e+02  1.42498834e+04
 -1.60038535e+04 -1.34482311e+04 -1.58201243e+04  1.76215166e+04
  6.57611834e+04  4.16734

aaaa 1 [-2842.61509358 -2806.83942453  1190.01876379 ...   953.44753037
  -279.22715776    21.34866455]
10
aaaa 2 [-1.20592561e+02 -3.37208075e+03 -9.23894083e+03 ...  9.60609692e+01
 -1.50912721e+02  1.33226763e-14]
10
aaaa 3 [ 1.92604714e+01  1.38268280e+02  2.69203650e+03 ... -1.80164053e+02
 -1.99502058e+02  1.94691465e-14]
10
aaaa 4 [-7.65117998e-02  1.79268349e+02  4.73894456e+03 -1.04842122e+02
  5.46068463e+03 -5.30714813e+03  2.39431885e+03  9.07577050e+03
  8.58586729e+03 -9.82724842e+03 -2.05697110e+01  4.15554275e+03
  7.64066172e+03  2.35771749e+03  9.48333831e+02  9.40568834e+03
 -3.05735362e+03  1.34834603e+03 -7.33991826e+02  6.90068822e+02
  1.45008982e+04  1.81721969e+04 -1.57947764e+04  1.20094083e+04
 -7.39573525e+03 -4.48554784e+03  3.41604211e+03  3.68272593e+03
 -3.20202494e+03 -6.11698036e+03  1.46762910e+03  7.28366353e+03
 -7.08815810e+03  6.26527321e+03  1.65627349e+04 -1.13002153e+04
 -5.94237820e+03  8.18745193e+04 -1.11871349e+05 -1.79980720e+03
  1.335571

aaaa 6 [-2.00652587e+00  2.32237683e+02  4.81370364e+03 -1.11026685e+03
  7.25235558e+04 -4.80528017e+04  1.35256865e+04  4.46778469e+04
 -5.55407600e+04  3.59279625e+04  1.87379826e+04  1.72939354e+05
 -2.78723775e+05  7.49704087e+04  2.45462509e+03 -1.35593901e+04
  6.75131062e+04  1.68809546e+05 -6.91039435e+04 -1.06414488e+05
  1.27711661e+05  3.27346529e+04 -4.89196527e+04 -4.60562770e+04
 -9.84984995e+04  6.30387521e+04 -1.21405192e+05 -6.67205598e+04
 -1.18767110e+04 -2.77684390e+04 -3.41385508e+03 -7.70325146e+04
  1.62262770e+05 -1.83371478e+06  1.41556856e+06 -5.84023959e+05
  9.22252335e+04 -7.07293874e+04 -9.32280976e+05  4.96861209e+05
 -9.37159704e+04 -2.31363379e+04  4.70571725e+03 -1.32741439e+04
  1.77051866e+04  1.91683934e+04 -1.16295951e+04  1.57929341e+04
 -4.26296506e+04  1.03396305e+05  3.91640315e+03 -1.20814832e+04
  6.12161638e+03 -1.29779454e+04  3.13701337e+04  1.21011715e+04
  1.04446019e+04  6.44302091e+04 -8.10354629e+04  4.08862010e+04
 -5.85930479e+03 -

aaaa 2 [-1.20592561e+02 -3.37208075e+03 -9.23894083e+03 ...  9.60609692e+01
 -1.50912721e+02  1.33226763e-14]
10
aaaa 3 [ 1.92604714e+01  1.38268280e+02  2.69203650e+03 ... -1.80164053e+02
 -1.99502058e+02  1.94691465e-14]
10
aaaa 4 [-7.65117998e-02  1.79268349e+02  4.73894456e+03 -1.04842122e+02
  5.46068463e+03 -5.30714813e+03  2.39431885e+03  9.07577050e+03
  8.58586729e+03 -9.82724842e+03 -2.05697110e+01  4.15554275e+03
  7.64066172e+03  2.35771749e+03  9.48333831e+02  9.40568834e+03
 -3.05735362e+03  1.34834603e+03 -7.33991826e+02  6.90068822e+02
  1.45008982e+04  1.81721969e+04 -1.57947764e+04  1.20094083e+04
 -7.39573525e+03 -4.48554784e+03  3.41604211e+03  3.68272593e+03
 -3.20202494e+03 -6.11698036e+03  1.46762910e+03  7.28366353e+03
 -7.08815810e+03  6.26527321e+03  1.65627349e+04 -1.13002153e+04
 -5.94237820e+03  8.18745193e+04 -1.11871349e+05 -1.79980720e+03
  1.33557104e+04  1.71005877e+03 -3.46114189e+03  5.84347762e+03
 -2.14588354e+04  1.02233590e+04  5.67727328e+03  2.

aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+05  2.38931029e+04 -5.52655575e+04  5.24653361e+04
 -1.05941210e+04 -

  7.11558999e+03 -2.33139272e+02 -3.13720362e+02 -5.65233285e-14]
10
aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+

aaaa 7 [-1.84024156e+00  2.52819156e+02  9.91109611e+03 -4.80872467e+03
 -1.07937401e+05 -2.71994222e+04  5.52995023e+04  6.70255238e+05
 -2.80398113e+05 -1.29767648e+05  2.65422783e+05 -1.87040464e+05
  8.38596062e+04 -8.14143215e+04  1.21183163e+04  9.09168366e+03
  5.01616085e+05  3.94615579e+05 -2.52638968e+05 -2.70847636e+05
  1.68695763e+05  4.14805611e+05  2.10549877e+03 -8.89572582e+04
  2.15340150e+04  6.79257981e+03  1.43792723e+05 -4.17885092e+04
  2.06670935e+04  1.51761040e+04 -6.04848165e+04  6.06807980e+04
  8.54800326e+02 -2.16297348e+04  1.91881569e+04 -3.97744552e+04
  2.19361561e+04 -6.56060118e+04  3.19809173e+04 -9.91774096e+01
 -4.21137982e+04  1.22078605e+04  4.22927449e+04 -1.63955398e+04
 -4.10879054e+04  9.73762777e+03 -4.36616734e+03  4.19969289e+03
 -4.24050221e+02  2.32376334e+04  1.52882881e+04 -6.97552704e+04
 -1.03243339e+04  5.63582792e+03 -5.28247527e+02  1.42498834e+04
 -1.60038535e+04 -1.34482311e+04 -1.58201243e+04  1.76215166e+04
  6.57611834e+04  

aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+05  2.38931029e+04 -5.52655575e+04  5.24653361e+04
 -1.05941210e+04 -

aaaa 5 [-1.34715841e+00  2.58812135e+02  4.71436326e+03 -1.43375399e+02
  4.82487805e+03 -4.88363517e+04  2.45243203e+03  8.59769162e+03
 -4.37400229e+03  1.07390671e+04 -3.15953727e+03  1.48019750e+04
  8.86273795e+02 -1.02170517e+04  2.31177613e+04  1.55451560e+04
 -1.29816393e+04  1.36113349e+04 -9.19778925e+03 -7.59656071e+04
  3.75050653e+05 -2.06391432e+05  4.80975450e+04 -2.27054075e+04
  1.15206088e+03 -2.41828525e+03  5.14690198e+03 -5.39463134e+04
 -7.24133511e+04  3.40077418e+03 -1.42489190e+05  7.15959966e+04
 -9.40437158e+04  3.02035555e+04  2.67735343e+03 -2.16936481e+04
  7.59951397e+04 -1.29309741e+03 -4.99219986e+04 -1.12378059e+04
  1.06133452e+03 -1.10307534e+03 -2.22086166e+04 -1.51277547e+04
  9.24366464e+04 -1.34633721e+04  4.75474925e+04 -9.72980767e+03
 -6.66508407e+04  5.14023084e+03 -1.04871902e+04  5.73128042e+03
  1.71747326e+04  7.13558965e+04 -1.04008125e+05  4.89248698e+04
  1.18036953e+04  9.33137923e+03 -2.29612228e+04 -4.86221014e+03
 -1.80016315e+04  

aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+05  2.38931029e+04 -5.52655575e+04  5.24653361e+04
 -1.05941210e+04 -

aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+05  2.38931029e+04 -5.52655575e+04  5.24653361e+04
 -1.05941210e+04 -

aaaa 8 [ 6.40419969e+04  6.40541894e+04  6.44306980e+04  6.14761016e+04
  6.79700804e+04  5.42253849e+04  2.84320186e+04 -2.84865056e+05
 -9.27171323e+05 -1.86834150e+05  1.19970163e+06  1.81058494e+05
 -2.80844499e+05  1.69760426e+05  1.02570951e+04 -4.16823705e+05
  8.60479596e+05 -1.14340834e+05 -5.83836477e+05  1.09131887e+06
 -1.49247039e+06  4.23369733e+05  2.08050545e+06 -1.11694730e+06
 -6.70965097e+05 -4.09873320e+04  8.93791581e+03 -9.96716760e+04
  1.51656805e+04  1.36593870e+05 -3.91795971e+04 -3.95753786e+03
  1.95063049e+05 -1.79940168e+05 -5.24156716e+04 -9.86797485e+03
  2.02202111e+04  8.13928591e+04  1.05691370e+05 -3.49143276e+04
 -4.26764227e+04  4.41542906e+03 -7.96566060e+04 -4.01593747e+04
  4.08235001e+03  6.10538618e+04  3.19894751e+04 -7.40552943e+04
 -1.51585765e+04  1.38228336e+04  3.08731440e+04  2.24134264e+04
 -6.37823622e+04 -4.03895011e+05  3.87940589e+04  2.22799057e+05
  1.34087471e+05  2.38931029e+04 -5.52655575e+04  5.24653361e+04
 -1.05941210e+04 -

In [ ]:
data_obj.write_features